tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem

http:
  routers:
    dev-router:
      rule: "Host(`localhost`)"
      service: dev-service
      tls: true
      entrypoints:
        - websecure
  
  services:
    dev-service:
      loadBalancer:
        servers:
          - url: http://localhost:80 
