http:
  routers:
    auth:
      rule: "PathPrefix(`/auth`)"
      service: auth-service

    users:
      rule: "PathPrefix(`/users`)"
      service: users-service

    redirect:
      rule: "PathPrefix(`/redirect`)"
      service: redirect-service
    
    profiles:
      rule: "PathPrefix(`/profiles`)"
      service: profiles-service

    tasks:
      rule: "PathPrefix(`/tasks`)"
      service: tasks-service
    
    friends:
      rule: "PathPrefix(`/friends`)"
      service: friends-service

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8000"

    profiles-service:
      loadBalancer:
        servers:
          - url: "http://profiles-service:8000"

    redirect-service:
      loadBalancer:
        servers:
          - url: "http://redirect-service:8000"

    users-service:
      loadBalancer:
        servers:
          - url: "http://users-service:8000"
    
    tasks-service:
      loadBalancer:
        servers:
          - url: "http://tasks-service:8000"

    friends-service:
      loadBalancer:
        servers:
          - url: "http://friends-service:8000"
