http:
  routers:
    auth:
      rule: "PathPrefix(`/auth`)"
      service: auth-service

    users:
      rule: "PathPrefix(`/users`)"
      service: users-service

    redirect:
      rule: "PathPrefix(`/redirect`)"
      service: redirect-service

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "https://auth.azure.com"

    profiles-service:
      loadBalancer:
        servers:
          - url: "https://profiles.azure.com"

    redirect-service:
      loadBalancer:
        servers:
          - url: "https://redirect.azure.com"
    
    users-service:
      loadBalancer:
        servers:
          - url: "https://users.azure.com"
