[project]
name = "projectanty"
version = "0.0.1"
description = "A social task management app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.0",
    "argon2-cffi>=25.1.0",
    "azure-cosmos>=4.9.0",
    "cryptography>=46.0.2",
    "fastapi>=0.118.2",
    "httpx>=0.28.1",
    "passlib[argon2]>=1.7.4",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.12.0",
    "pyjwt[cryptography]>=2.10.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "pytest-subtests>=0.14.2",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "ruff>=0.14.0",
    "ty>=0.0.1a21",
    "uvicorn>=0.37.0",
]
