services:
  # --------- Reverse Proxy (Traefik) ----------
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    ports:
      - "80:80"        # HTTP
      - "8080:8080"    # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      # - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

  # --------- Hello Service ----------
  hello-service:
    build:
      context: ./hello-world/
      dockerfile: Dockerfile.dev
    container_name: hello-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`hello.localhost`)"
      - "traefik.http.routers.hello.entrypoints=web"
      # - "traefik.http.routers.hello.entrypoints=websecure"
      # - "traefik.http.routers.hello.tls.certresolver=letsencrypt"
      - "traefik.http.services.hello.loadbalancer.server.port=8000"
    depends_on:
      - traefik
    restart: unless-stopped

networks:
  default:
    name: traefik-net
