services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/traefik/traefik.prod.yml"
    volumes:
      - "./traefik/traefik.prod.yml:/traefik/traefik.prod.yml:ro"
