services:
  traefik:
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/traefik/traefik.dev.yml"
    ports:
      - "8080:8080"
    volumes:
      - "./traefik/traefik.dev.yml:/traefik/traefik.dev.yml:ro"

  auth-service:
    build:
      dockerfile: auth_service/Dockerfile.dev
    container_name: auth-service
    expose:
      - "8000"
    restart: unless-stopped
  
  profiles-service:
    build:
      dockerfile: profiles_service/Dockerfile.dev
    container_name: profiles-service
    expose:
      - "8000"
    restart: unless-stopped
  
  friends-service:
    build:
      dockerfile: friends_service/Dockerfile.dev
    container_name: friends-service
    expose:
      - "8000"
    restart: unless-stopped
  
  redirect-service:
    build:
      dockerfile: redirect_service/Dockerfile.dev
    container_name: redirect-service
    expose:
      - "8000"
    restart: unless-stopped
  
  users-service:
    build:
      dockerfile: users_service/Dockerfile.dev
    container_name: users-service
    expose:
      - "8000"
    restart: unless-stopped

  tasks-service:
    build:
      dockerfile: tasks_service/Dockerfile.dev
    container_name: tasks-service
    expose:
      - "8000"
    restart: unless-stopped
