# this doesn't work yet
services:
  traefik:
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=teamanty50@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    volumes:
      - "./traefik/traefik.prod.yml:/traefik.yml:ro"
      - "./traefik/acme.json:/letsencrypt/acme.json"

  hello-service:
    labels:
      - "traefik.http.routers.hello.rule=Host(`hello.anty.com`)"
      - "traefik.http.routers.hello.entrypoints=websecure"
      - "traefik.http.routers.hello.tls.certresolver=letsencrypt"
