services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-net
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/traefik/traefik.dev.yml"
    volumes:
      - "./traefik/traefik.dev.yml:/traefik/traefik.dev.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth-service:
    build:
      dockerfile: auth_service/Dockerfile.dev
    container_name: auth-service
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - traefik-net
  
  profiles-service:
    build:
      dockerfile: profiles_service/Dockerfile.dev
    container_name: profiles-service
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - traefik-net
  
  redirect-service:
    build:
      dockerfile: redirect_service/Dockerfile.dev
    container_name: redirect-service
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - traefik-net
  
  users-service:
    build:
      dockerfile: users_service/Dockerfile.dev
    container_name: users-service
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge