services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  hello-service:
    build:
      context: ./hello-world/
      dockerfile: Dockerfile.dev
    container_name: hello-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`hello.localhost`)"
      - "traefik.http.services.hello.loadbalancer.server.port=8000"
    depends_on:
      - traefik
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth/
      dockerfile: Dockerfile.dev
    container_name: auth-service
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"
    depends_on:
      - traefik
    restart: unless-stopped


networks:
  default:
    name: traefik-net
