[project]
name = "backend"
version = "0.1.0"
description = "ProjectANTY backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "python-dotenv>=1.1.1",
    "ruff>=0.14.0",
    "ty>=0.0.1a22",
]

[project.optional-dependencies]
auth_service = [
    "aiohttp>=3.13.0",
    "azure-cosmos>=4.14.0",
    "email-validator>=2.3.0",
    "httpx>=0.28.1",
    "pwdlib[argon2]>=0.2.1",
    "pydantic-settings>=2.11.0",
    "pyjwt[crypto]>=2.10.1",
    "python-multipart>=0.0.20",
]

users_service = [
    "aiohttp>=3.13.0",
    "azure-cosmos>=4.14.0",
    "pydantic-settings>=2.11.0",
    "email-validator>=2.3.0",
    "httpx>=0.28.1",
]

[tool.ty.terminal]
output-format = "full"
error-on-warning = true 

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # allow raising exceptions without 'from e' for HTTPException
    "E402",
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true