name: Users Backend Pipelines

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Make sure code abides by the ruff format.
  users-backend:
    name: Lint, Typecheck, Unit Test.
    runs-on: ubuntu-latest
    environment: "ANTY Backend Environment"

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
    
      - name: Install uv.
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Users checks.
        env:
          COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
          COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
          COSMOSDB_DATABASE_NAME: ${{ secrets.COSMOSDB_DATABASE_NAME }}
          AUTH_SERVICE_URL: ${{ vars.AUTH_SERVICE_URL }}
          INTERSERVICE_KEY: ${{ secrets.INTERSERVICE_KEY }}
          PROFILES_SERVICE_URL: ${{ vars.PROFILES_SERVICE_URL }}
        run: |
          cd backend/users_service
          uv sync --dev
          uv run ruff check
          uv run ty check
          uv run pytest
