FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

# Copy shared package first so it can be installed before service code
COPY ./shared ./shared

# Copy service code
COPY ./auth_service ./auth_service

WORKDIR /app/auth_service

RUN uv sync

RUN groupadd -r anty && useradd -r -m -g anty anty

USER anty

CMD ["uv", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0","--port", "8000"]
