FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.9.5 /uv /uvx /bin/

WORKDIR /app

# Copy source code
COPY ./shared ./shared
COPY ./profiles_service ./profiles_service

WORKDIR /app/profiles_service

RUN uv sync --locked

CMD ["uv", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0","--port", "8000"]
