FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

# Copy shared package first so it can be installed before service code
COPY ./shared ./shared

# Copy service code
COPY ./profiles_service ./profiles_service

WORKDIR /app/profiles_service

# Install both with uv
# RUN cd /app/shared && uv sync

RUN uv sync

# EXPOSE 8000

RUN groupadd -r anty && useradd -r -m -g anty anty

USER anty

CMD ["uv", "run", "fastapi", "dev", "src/main.py", "--host", "0.0.0.0","--port", "8000"]
