name: Auth Backend Pipelines

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Make sure code abides by the ruff format.
  auth-backend:
    name: Lint, Typecheck, Unit Test.
    runs-on: ubuntu-latest
    environment: "ANTY Auth Backend"

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
    
      - name: Install uv.
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Auth checks.
        env:
          COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
          COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
          COSMOSDB_DATABASE_NAME: ${{ secrets.COSMOSDB_DATABASE_NAME }}

          TOKEN_PUBLIC_KEY: ''
          TOKEN_PRIVATE_KEY: ''
          TOKEN_ALGORITHM: ${{ secrets.TOKEN_ALGORITHM }}
          ACCESS_TOKEN_EXPIRATION_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRATION_MINUTES }}
          REFRESH_TOKEN_EXPIRATION_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRATION_DAYS }}
        run: |
          cd backend/auth_service
          uv sync --dev && uv pip install -e ../shared
          uv run ruff check
          uv run ty check
          uv run pytest
