name: Auth Backend Pipelines

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Make sure code abides by the ruff format.
  auth-backend:
    name: Lint, Typecheck, Unit Test.
    runs-on: ubuntu-latest
    environment: "ANTY Backend Environment"

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
    
      - name: Install uv.
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Auth checks.
        env:
          COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
          COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
          COSMOSDB_DATABASE_NAME: ${{ secrets.COSMOSDB_DATABASE_NAME }}
          AUTH_SERVICE_URL: ${{ vars.AUTH_SERVICE_URL }}
          AUTH_EXTERNAL_URL: ''
          INTERSERVICE_KEY: ${{ secrets.INTERSERVICE_KEY }}

          TOKEN_PUBLIC_KEY: ''
          TOKEN_PRIVATE_KEY: ''
          TOKEN_ALGORITHM: ${{ vars.TOKEN_ALGORITHM }}
          ACCESS_TOKEN_EXPIRATION_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRATION_MINUTES }}
          REFRESH_TOKEN_EXPIRATION_DAYS: ${{ vars.REFRESH_TOKEN_EXPIRATION_DAYS }}

          FRONTEND_URL: ''
          SMTP_USER: ${{ vars.SMTP_USER }}
          SMTP_PASSWORD: ${{ vars.SMTP_PASSWORD }}
        run: |
          cd backend/auth_service
          uv sync --dev
          uv run ruff check
          uv run ty check
          uv run pytest
