name: Build & Push Service

on:
  workflow_call:
    inputs:
      service:
        description: "Service to build and push"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "Azure Deployment Environment"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push Service
        run: |
          docker build -f backend/${{ inputs.service }}_service/Dockerfile \
            -t ${{ vars.ACR_URL }}/${{ inputs.service }}-service:latest \
            backend
          docker push ${{ vars.ACR_URL }}/${{ inputs.service }}-service:latest

      - name: Update Container
        run: |
          az containerapp update \
            --name ${{ inputs.service }}-service \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --image ${{ vars.ACR_URL }}/${{ inputs.service }}-service:latest \
            --cpu 0.25 \
            --memory 0.5Gi \
            --min-replicas 1 \
            --max-replicas 3