name: Profiles Service Deployment Orchestration

on:
  push:
    branches: ["main"]
    paths: ["backend/profiles_service/**", "backend/shared/**"]

jobs:
  deploy:
    uses: ./.github/workflows/deployment_orchestration.yml
    with:
      service: "profiles"
    secrets: inherit
    vars: inherit