name: Image Service Deployment Orchestration

on:
  push:
    branches: ["main"]
    paths: ["backend/image_service/**", "backend/shared/**"]

jobs:
  deploy:
    uses: ./.github/workflows/deployment_orchestration.yml
    with:
      service: "image"
    secrets: inherit
    