name: Build & Push Profiles Service

on:
  push:
    branches: ["main"]
    paths: ["backend/profiles_service/**"]
  workflow_dispatch:

jobs:
  build-and-push-profiles:
    name: Build and push service to Container Registry
    runs-on: ubuntu-latest
    environment: "Azure Deployment Environment"
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push
        run: |
          docker build -f backend/profiles_service/Dockerfile \
            -t ${{ vars.ACR_URL }}/profiles-service:latest \
            backend
          docker push ${{ vars.ACR_URL }}/profiles-service:latest

      - name: Scale down running app
        run: |
          az containerapp scale \
            --name profiles-service \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --min-replicas 0 \
            --max-replicas 0

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name profiles-service \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --image ${{ vars.ACR_URL }}/profiles-service:latest \
            --cpu 0.25 \
            --memory 0.5Gi \
            --min-replicas 1 \
            --max-replicas 3
      
      - name: Scale back up  
        run: |
          az containerapp scale \
            --name profiles-service \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --min-replicas 1 \
            --max-replicas 3