name: Shared Validation

on:
  push:
    branches: ["main"]
    paths: ["backend/shared/**"]
  pull_request:
    branches: ["main"]
    paths: ["backend/shared/**"]

jobs:
  # Make sure code abides by the ruff format.
  shared-validation:
    name: Lint, Typecheck, Unit Test.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
    
      - name: Install uv.
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Shared checks.
        run: |
          cd backend/shared
          uv sync --dev
          uv run ruff check
          uv run ty check
