name: Tasks Backend Pipelines

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Make sure code abides by the ruff format.
  tasks-backend:
    name: Lint, Typecheck, Unit Test.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
    
      - name: Install uv.
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Tasks checks.
        run: |
          cd backend/tasks_service
          uv sync --dev
          uv run ruff check
          uv run ty check
          uv run pytest
