name: Test Auth Build Workflow

on:
  workflow_dispatch:   # always manually trigger
  push:
    branches:
      - main
      - yn-backend-deployment
    paths:
      - 'backend/auth_service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow is running!"
