name: Build & Push Users Service

on:
  push:
    branches: ["main"]
    paths: ["backend/users_service/**"]
  workflow_dispatch:

jobs:
  build-and-push-users:
    name: Build and push service to Container Registry
    runs-on: ubuntu-latest
    environment: "Azure Deployment Environment"
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Set up Azure PowerShell
        uses: azure/powershell@v2

      - name: Login to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push Users Service
        run: |
          docker build -f backend/users_service/Dockerfile \
            -t ${{ vars.ACR_URL }}/users-service:latest \
            backend
          docker push ${{ vars.ACR_URL }}/users-service:latest

      - name: Stop Users Container App (PowerShell)
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Stop-AzContainerApp -ResourceGroupName ${{ vars.AZURE_RESOURCE_GROUP }} -Name users-service
          azPSVersion: "latest"

      - name: Deploy to Users Container App
        run: |
          az containerapp update \
            --name users-service \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --image ${{ vars.ACR_URL }}/users-service:latest \
            --cpu 0.25 \
            --memory 0.5Gi \
            --min-replicas 1 \
            --max-replicas 3

      - name: Start Users Container App (PowerShell)
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Start-AzContainerApp -ResourceGroupName ${{ vars.AZURE_RESOURCE_GROUP }} -Name users-service
          azPSVersion: "latest"
