FROM python:3.12-slim

RUN pip install --no-cache-dir uv

WORKDIR /app

# Copy service code
COPY ./redirect_service ./redirect_service

WORKDIR /app/redirect_service

RUN uv sync

RUN groupadd -r anty && useradd -r -m -g anty anty

USER anty

CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
